[book]
authors = ["shilangyu"]
language = "en"
multilingual = false
src = "src"
title = "Uni notes"

[output.html]
# mathjax-support = true

[preprocessor.katex]
command = "python katex.py"
renderer = ["html"]
